from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class QuranMetadataRepository(Protocol):
    def get_surah_meta(self, surah_no: int) -> dict[str, Any] | None: ...
    def list_surahs(self) -> dict[int, dict[str, Any]]: ...


class QuranTextRepository(Protocol):
    def get_ayah(self, surah_no: int, ayah_no: int) -> dict[str, Any] | None: ...
    def get_span(self, surah_no: int, ayah_start: int, ayah_end: int) -> list[dict[str, Any]]: ...


class QuranTranslationRepository(Protocol):
    def get_translation_ayah(self, surah_no: int, ayah_no: int, *, language: str = "en") -> dict[str, Any] | None: ...
    def get_translation_span(self, surah_no: int, ayah_start: int, ayah_end: int, *, language: str = "en") -> dict[str, Any]: ...


class QuranRuntimeAssetsRepository(Protocol):
    def get_quran_path(self, *, label: str = "simple") -> Path: ...
    def get_passage_path(self, *, label: str = "simple") -> Path: ...
